blueprint:
  name: Fenster + Rollladen + Heizung (URL)
  description: Steuerung von Rollladen und Heizung beim Lüften. URLs direkt eingeben.
  domain: automation
  input:
    fenster_sensor:
      name: Fenster Sensor
      selector:
        entity:
          domain: binary_sensor
    rollladen_cover:
      name: Rollladen
      selector:
        entity:
          domain: cover
    gespeicherte_position:
      name: Helfer für gespeicherte Position
      selector:
        entity:
          domain: input_number
    heizung_auf_url:
      name: Heizung offen (URL)
      selector:
        text: {}
    heizung_zu_url:
      name: Heizung zu (URL)
      selector:
        text: {}

trigger:
  - platform: device
    type: opened
    device_id: !input fenster_sensor
    entity_id: !input fenster_sensor
    domain: binary_sensor
    id: fenster_auf
  - platform: device
    type: not_opened
    device_id: !input fenster_sensor
    entity_id: !input fenster_sensor
    domain: binary_sensor
    id: fenster_zu

mode: restart

action:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - fenster_auf
        sequence:
          # Rollladenposition speichern
          - service: input_number.set_value
            target:
              entity_id: !input gespeicherte_position
            data:
              value: "{{ state_attr('cover.shutter_wz_2', 'current_position') | int }}"
          # Rollladen hochfahren
          - service: cover.open_cover
            target:
              entity_id: !input rollladen_cover
          # Heizung sperren
          - service: uri
            data:
              url: !input heizung_auf_url
              method: GET

      - conditions:
          - condition: trigger
            id:
              - fenster_zu
        sequence:
          - delay: "00:00:03"
          # Rollladenposition wiederherstellen
          - service: cover.set_cover_position
            target:
              entity_id: !input rollladen_cover
            data:
              position: "{{ states('input_number.shutter_wz_saved_position') | int }}"
          # Heizung frei
          - service: uri
            data:
              url: !input heizung_zu_url
              method: GET
