blueprint:
  name: Fenster + Rollladen + Heizung (URL)
  description: Steuerung von Rollladen und Heizung beim Lüften eines Fensters. URLs für Heizung direkt eintragbar.
  domain: automation
  input:
    fenster_sensor:
      name: Fenster Sensor
      description: Binary Sensor, der das Fenster auf/zu meldet
      selector:
        entity:
          domain: binary_sensor
    rollladen_cover:
      name: Rollladen
      description: Cover Entität des Rollladens
      selector:
        entity:
          domain: cover
    gespeicherte_position:
      name: Helfer für gespeicherte Position
      description: Input Number, um Rollladenposition zwischenzuspeichern
      selector:
        entity:
          domain: input_number
    heizung_auf_url:
      name: Heizung Fenster offen (URL)
      description: URL, die aufgerufen wird, wenn das Fenster geöffnet wird (Heizung sperren / SetOverride)
      default: "http://**IP**/rpc/BluTrv.Call?id=**ID**&method=TRV.SetOverride&params={\"id\":0}"
      selector:
        text:
          multiline: false
    heizung_zu_url:
      name: Heizung Fenster zu (URL)
      description: URL, die aufgerufen wird, wenn das Fenster geschlossen wird (Heizung frei / ClearOverride)
      default: "http://**IP**/rpc/BluTrv.Call?id=**ID**&method=TRV.ClearOverride&params={\"id\":0}"
      selector:
        text:
          multiline: false

trigger:
  - platform: device
    type: opened
    device_id: !input fenster_sensor
    entity_id: !input fenster_sensor
    domain: binary_sensor
    id: fenster_auf
  - platform: device
    type: not_opened
    device_id: !input fenster_sensor
    entity_id: !input fenster_sensor
    domain: binary_sensor
    id: fenster_zu

mode: restart

action:
  - choose:
      # Fenster auf
      - conditions:
          - condition: trigger
            id:
              - fenster_auf
        sequence:
          - condition: template
            value_template: "{{ state_attr(!input rollladen_cover, 'current_position') | int < 100 }}"
          - service: input_number.set_value
            target:
              entity_id: !input gespeicherte_position
            data:
              value: "{{ state_attr(!input rollladen_cover, 'current_position') | int }}"
          - service: cover.open_cover
            target:
              entity_id: !input rollladen_cover
          - service: uri
            data:
              url: !input heizung_auf_url
              method: GET

      # Fenster zu
      - conditions:
          - condition: trigger
            id:
              - fenster_zu
        sequence:
          - delay: "00:00:03"   # Kurzes Kipp-Öffnen abfangen
          - service: cover.set_cover_position
            target:
              entity_id: !input rollladen_cover
            data:
              position: "{{ states(!input gespeicherte_position) | int }}"
          - service: uri
            data:
              url: !input heizung_zu_url
              method: GET
