blueprint:
  name: Fenster + Rollladen + Heizung (über rest_command)
  description: Steuerung von Rollladen + Heizung beim Lüften eines Fensters
  domain: automation
  input:
    fenster_sensor:
      name: Fenster Sensor
      selector:
        entity:
          domain: binary_sensor
    rollladen_cover:
      name: Rollladen
      selector:
        entity:
          domain: cover
    gespeicherte_position:
      name: Helfer für gespeicherte Position
      selector:
        entity:
          domain: input_number
    heizung_auf_command:
      name: Heizung Fenster offen
      selector:
        entity:
          domain: rest_command
    heizung_zu_command:
      name: Heizung Fenster zu
      selector:
        entity:
          domain: rest_command

trigger:
  - platform: device
    type: opened
    device_id: !input fenster_sensor
    entity_id: !input fenster_sensor
    domain: binary_sensor
    id: fenster_auf
  - platform: device
    type: not_opened
    device_id: !input fenster_sensor
    entity_id: !input fenster_sensor
    domain: binary_sensor
    id: fenster_zu

mode: restart

action:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - fenster_auf
        sequence:
          - condition: template
            value_template: "{{ state_attr(!input rollladen_cover, 'current_position') | int < 100 }}"
          - service: input_number.set_value
            target:
              entity_id: !input gespeicherte_position
            data:
              value: "{{ state_attr(!input rollladen_cover, 'current_position') | int }}"
          - service: cover.open_cover
            target:
              entity_id: !input rollladen_cover
          - service: !input heizung_auf_command

      - conditions:
          - condition: trigger
            id:
              - fenster_zu
        sequence:
          - delay: "00:00:03"
          - service: cover.set_cover_position
            target:
              entity_id: !input rollladen_cover
            data:
              position: "{{ states(!input gespeicherte_position) | int }}"
          - service: !input heizung_zu_command
